; PlatformIO Project Configuration File

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

; WiFi Configuration
build_flags =
    -DWIFI_SSID=\"Wokwi-GUEST\"
    -DWIFI_PASSWORD=\"\"
    -DSERVER_URL=\"http://192.168.100.50:3000\"
lib_deps =
    bblanchon/ArduinoJson

; Serial Monitor
monitor_speed = 115200